# Generated by Django 4.2 on 2023-04-11 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tracker',
            new_name='LocationData',
        ),
    ]
